"""Regenerate scripts/tz_countries.py from the system tzdata.

    python scripts/build_tz_map.py

Reads /usr/share/zoneinfo/zone.tab — the tzdb table that carries exactly one ISO
3166-1 alpha-2 country code per zone — and prunes it to the states that have a
roll-call record in dashboard/data.js, so every emitted zone resolves to a country
the dashboard can actually open.

Legacy aliases are curated in ALIASES below, not derived. Deriving them by comparing
zone-file contents looks tempting and is wrong: Asia/Rangoon and Indian/Cocos are
byte-identical (+06:30, no DST), so a content match files Myanmar under the Cocos
Islands. Each alias here is checked to exist in tzdata and to not already be canonical.

Re-run after a tzdb update, or when a state first appears in the vote data.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ZONEINFO = Path("/usr/share/zoneinfo")
OUT = ROOT / "scripts" / "tz_countries.py"

# Zone names browsers have historically returned that zone.tab no longer lists.
ALIASES = {
    "Asia/Calcutta": "IN", "Asia/Saigon": "VN", "Asia/Rangoon": "MM",
    "Asia/Katmandu": "NP", "Asia/Dacca": "BD", "Asia/Istanbul": "TR",
    "Asia/Chungking": "CN", "Asia/Chongqing": "CN", "Asia/Harbin": "CN",
    "Asia/Macao": "MO", "Asia/Ulan_Bator": "MN", "Asia/Thimbu": "BT",
    "Asia/Ashkhabad": "TM", "Europe/Kiev": "UA", "Europe/Uzhgorod": "UA",
    "Europe/Zaporozhye": "UA", "Europe/Nicosia": "CY",
    "America/Buenos_Aires": "AR", "America/Cordoba": "AR", "America/Rosario": "AR",
    "America/Mendoza": "AR", "America/Catamarca": "AR", "America/Jujuy": "AR",
    "America/Ensenada": "MX", "America/Santa_Isabel": "MX",
    "America/Porto_Acre": "BR", "Africa/Timbuktu": "ML", "Africa/Asmera": "ER",
    "Atlantic/Jan_Mayen": "NO", "Pacific/Ponape": "FM", "Pacific/Truk": "FM",
}

HEADER = '''"""IANA time-zone -> ISO 3166-1 alpha-2, for guessing which country's profile to
open on the Country tab.

GENERATED by scripts/build_tz_map.py from tzdb {version} — do not edit by hand.

A time zone is a better location signal than a browser locale but still only a guess:
a reader on a VPN, or one who never changed a laptop's zone after moving, gets the
wrong country. The dashboard therefore labels a guessed country as guessed.
"""

TZ_TO_ISO2 = {{
{body}
}}
'''


def main():
    tab = ZONEINFO / "zone.tab"
    if not tab.exists():
        raise SystemExit(f"{tab} not found — this script needs system tzdata")
    version = (ZONEINFO / "+VERSION").read_text().strip() if (ZONEINFO / "+VERSION").exists() else "unknown"

    canon = {}
    for ln in tab.read_text().splitlines():
        if ln.startswith("#") or not ln.strip():
            continue
        parts = ln.split("\t")
        if len(parts) >= 3:
            canon[parts[2].strip()] = parts[0].strip()

    for z in ALIASES:
        if not (ZONEINFO / z).exists():
            raise SystemExit(f"alias {z} is not in this tzdata — remove it or fix the name")
        if z in canon:
            raise SystemExit(f"alias {z} is canonical in zone.tab — drop it from ALIASES")

    payload = json.loads((ROOT / "dashboard" / "data.js")
                         .read_text(encoding="utf-8")[len("window.DATA = "):]
                         .rstrip().rstrip(";"))
    have = set(payload["iso2"])

    full = {**canon, **ALIASES}
    keep = {z: c for z, c in sorted(full.items()) if c in have}
    missing = sorted(have - set(keep.values()))

    lines, line = [], "    "
    for z, c in keep.items():
        piece = f'"{z}": "{c}", '
        if len(line) + len(piece) > 96:
            lines.append(line.rstrip()); line = "    "
        line += piece
    if line.strip():
        lines.append(line.rstrip())

    OUT.write_text(HEADER.format(version=version, body="\n".join(lines)), encoding="utf-8")
    print(f"{OUT.relative_to(ROOT)}: {len(keep)} zones from tzdb {version}")
    print(f"  covers {len(set(keep.values()))} of {len(have)} states"
          + (f"; NO zone for {missing}" if missing else "; every state covered"))


if __name__ == "__main__":
    main()
